[lint]
ignore = [
    "BLE001",
    "PERF102",
    "F841",
    "TRY004",
    "RUF059",
    "C414",
    "S110",
    "SIM102",
    "RUF012",
    "DTZ007",
    "SIM113",
    "PIE810",
    "B008",
    "UP017"
]