"""
Data Lake API Endpoints
Parquet columnar file inspection, status, and manual flush.
"""

from typing import Any

from fastapi import APIRouter, Depends

from ulpf.apps.api.auth import get_current_user, require_roles
from ulpf.apps.api.routes.events import get_orchestrator
from ulpf.packages.schemas.models import UserRole

router = APIRouter(prefix="/datalake", tags=["Data Lake & Parquet"])


@router.get("/files", response_model=list[dict[str, Any]])
def list_parquet_files(user: dict[str, Any] = Depends(get_current_user)):
    """Lists all partitioned Parquet files generated by the ULPF Data Lake writer."""
    orch = get_orchestrator()
    return orch.data_lake.list_parquet_files()


@router.post("/flush", response_model=dict[str, Any])
def flush_data_lake_buffer(
    user: dict[str, Any] = Depends(require_roles([UserRole.ADMIN, UserRole.OPERATOR])),
):
    """Flushes currently buffered in-memory events to a new Parquet file on disk."""
    orch = get_orchestrator()
    path = orch.flush_data_lake()
    if not path:
        return {"status": "empty", "message": "No pending events in buffer to flush"}
    return {"status": "success", "file_path": path}
